library identifier: 'jenkins-pipeline-demo-library@main', 
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/MijailStell/jenkins-pipeline-demo-library.git'])

crossPlatformBuild repoName: 'sixeyed/pi-psod-pipelines',
                   linuxContext: 'm4', 
                   windowsContext: 'm4'